"""Publishing assembly pipeline (S15a).

Assembles text-free illustrations + text content + StyleLock config
into finished PDFs (via Typst) and EPUBs (via ebooklib).

Text is ALWAYS overlaid by Typst — NEVER rendered inside illustrations (#49).
Illustration prompts use ``illustration_shows`` field, not raw page text (§42.3).
"""

from __future__ import annotations

import logging
import os
import subprocess
from pathlib import Path
from uuid import uuid4

from ebooklib import epub

from contracts.context import RollingContext, TrackedEntity
from contracts.publishing import (
    AgeGroup,
    NarrativeScaffold,
    PageScaffold,
    StyleLock,
    TextPlacementStrategy,
)

logger = logging.getLogger(__name__)

_REPO_ROOT = Path(__file__).resolve().parent.parent
_TEMPLATES_DIR = _REPO_ROOT / "templates" / "typst"
_FONTS_DIR = _REPO_ROOT / "assets" / "fonts"

# ---------------------------------------------------------------------------
# Strategy → Typst template mapping (§42.3)
# ---------------------------------------------------------------------------

STRATEGY_TEMPLATE_MAP: dict[TextPlacementStrategy, str] = {
    TextPlacementStrategy.text_always_below: "book_single_page.typ",
    TextPlacementStrategy.text_on_left: "book_facing_pages.typ",
    TextPlacementStrategy.text_overlay_with_reserved_zone: "book_full_bleed.typ",
}

# Page dimensions per strategy
_PAGE_DIMS: dict[TextPlacementStrategy, tuple[str, str]] = {
    TextPlacementStrategy.text_always_below: ("8.5in", "11in"),
    TextPlacementStrategy.text_on_left: ("8in", "10in"),
    TextPlacementStrategy.text_overlay_with_reserved_zone: ("8.5in", "8.5in"),
}


# ---------------------------------------------------------------------------
# Typst helpers
# ---------------------------------------------------------------------------


def _escape_typst(text: str) -> str:
    """Escape special characters for Typst content mode."""
    for char in ("\\", "#", "*", "_", "`", "$", "@", "<", ">"):
        text = text.replace(char, f"\\{char}")
    return text


def _compile_typst(source_path: Path, output_path: Path) -> Path:
    """Compile a Typst source file to PDF.

    Uses ``--root /`` so absolute image paths resolve correctly.
    """
    env = {**os.environ, "TYPST_FONT_PATHS": str(_FONTS_DIR)}
    result = subprocess.run(
        ["typst", "compile", "--root", "/", str(source_path), str(output_path)],
        capture_output=True,
        text=True,
        env=env,
        check=False,
    )
    if result.returncode != 0:
        logger.error("Typst compilation failed: %s", result.stderr)
        raise RuntimeError(f"Typst compilation failed: {result.stderr}")
    return output_path


def _typst_header(
    palette: list[str],
    font: str,
    title: str,
    author: str,
    age_group: str,
    page_width: str,
    page_height: str,
) -> str:
    """Generate the common Typst header (inputs + typography + page setup)."""
    primary = palette[0] if palette else "#264653"
    secondary = palette[1] if len(palette) > 1 else "#FFF8F0"
    accent = palette[2] if len(palette) > 2 else "#E76F51"
    return "\n".join([
        "// Generated by Vizier publishing assembly pipeline",
        "// Illustrations are ALWAYS text-free. Typst adds ALL text. (#49)",
        "",
        f'#let primary = rgb("{primary}")',
        f'#let secondary = rgb("{secondary}")',
        f'#let accent = rgb("{accent}")',
        f'#let heading-font = "{font}"',
        f'#let body-font = "{font}"',
        f'#let book-title = "{_escape_typst(title)}"',
        f'#let book-author = "{_escape_typst(author)}"',
        f'#let age-group = "{age_group}"',
        "",
        '#let body-size = if age-group == "3-5" { 20pt } else if age-group == "5-7" { 16pt } else { 14pt }',
        '#let body-leading = if age-group == "3-5" { 1.5em } else if age-group == "5-7" { 1.4em } else { 1.3em }',
        "",
        f"#set page(width: {page_width}, height: {page_height}, margin: (rest: 0pt), footer: none, header: none)",
        "#set text(font: body-font, size: body-size, fill: primary)",
        "#set par(leading: body-leading, spacing: 1.2em)",
        "",
    ])


# ---------------------------------------------------------------------------
# Per-page Typst generators (one per layout strategy)
# ---------------------------------------------------------------------------


def _title_page(strategy: TextPlacementStrategy, img_path: str) -> str:
    """Generate title page Typst source."""
    if strategy == TextPlacementStrategy.text_always_below:
        return "\n".join([
            "#page[",
            f'  #box(width: 100%, height: 55%, clip: true)[#image("{img_path}", width: 100%, height: 100%, fit: "cover")]',
            "  #rect(width: 100%, height: 45%, fill: primary)[",
            "    #align(center + horizon)[",
            "      #pad(x: 2cm)[",
            '        #text(font: heading-font, size: 36pt, weight: "bold", fill: secondary)[#book-title]',
            "        #v(0.8em)",
            "        #text(size: 14pt, fill: secondary.darken(10%))[#book-author]",
            "      ]",
            "    ]",
            "  ]",
            "]",
        ])
    if strategy == TextPlacementStrategy.text_on_left:
        return "\n".join([
            "#page[",
            "  #rect(width: 100%, height: 100%, fill: primary)[",
            "    #align(center + horizon)[",
            "      #pad(x: 2cm)[",
            '        #text(font: heading-font, size: 30pt, weight: "bold", fill: secondary)[#book-title]',
            "        #v(1em)",
            "        #text(size: 14pt, fill: secondary.darken(10%))[#book-author]",
            "      ]",
            "    ]",
            "  ]",
            "]",
        ])
    # text_overlay_with_reserved_zone
    return "\n".join([
        "#page[",
        "  #rect(width: 100%, height: 100%, fill: primary)[",
        "    #align(center + horizon)[",
        "      #pad(x: 2cm)[",
        '        #text(font: heading-font, size: 36pt, weight: "bold", fill: secondary)[#book-title]',
        "        #v(1em)",
        "        #text(size: 14pt, fill: secondary.darken(10%))[#book-author]",
        "      ]",
        "    ]",
        "  ]",
        "]",
    ])


def _story_page(
    strategy: TextPlacementStrategy,
    img_path: str,
    text: str,
    page_num: int,
) -> str:
    """Generate a single story page's Typst source."""
    escaped = _escape_typst(text)
    if strategy == TextPlacementStrategy.text_always_below:
        return "\n".join([
            f"// Page {page_num}",
            "#page[",
            f'  #box(width: 100%, height: 60%, clip: true)[#image("{img_path}", width: 100%, height: 100%, fit: "cover")]',
            "  #rect(width: 100%, height: 40%, fill: secondary)[",
            "    #pad(x: 2cm, top: 1cm, bottom: 0.8cm)[",
            "      #align(center + horizon)[" + escaped + "]",
            "    ]",
            f"    #place(bottom + center, dy: -0.4cm)[#text(size: 9pt, fill: luma(150))[{page_num}]]",
            "  ]",
            "]",
        ])
    if strategy == TextPlacementStrategy.text_on_left:
        # Facing pages: text on verso, illustration on recto
        return "\n".join([
            f"// Spread — page {page_num}",
            "#page[",
            "  #rect(width: 100%, height: 100%, fill: secondary)[",
            "    #pad(left: 1.5cm, right: 2cm, top: 3cm, bottom: 1.5cm)[",
            "      #align(horizon)[" + escaped + "]",
            "    ]",
            f"    #place(bottom + left, dx: 1.5cm, dy: -0.5cm)[#text(size: 9pt, fill: luma(150))[{page_num}]]",
            "  ]",
            "]",
            "#page[",
            f'  #image("{img_path}", width: 100%, height: 100%, fit: "cover")',
            f"  #place(bottom + right, dx: -0.5cm, dy: -0.5cm)[#text(size: 9pt, fill: luma(150))[{page_num + 1}]]",
            "]",
        ])
    # text_overlay_with_reserved_zone — full-bleed + overlay
    return "\n".join([
        f"// Page {page_num}",
        "#page[",
        f'  #image("{img_path}", width: 100%, height: 100%, fit: "cover")',
        "  #place(top + left, dy: 60%,",
        "    rect(width: 100%, height: 40%, fill: white.transparentize(20%))[",
        "      #pad(x: 1.2cm, y: 0.8cm)[",
        "        #align(center)[" + escaped + "]",
        "      ]",
        "    ]",
        "  )",
        f"  #place(bottom + right, dx: -0.5cm, dy: -0.3cm)[#text(size: 9pt, fill: white)[{page_num}]]",
        "]",
    ])


def _closing_page(
    strategy: TextPlacementStrategy,
    img_path: str,
    text: str,
    page_num: int,
) -> str:
    """Generate the closing page Typst source."""
    escaped = _escape_typst(text)
    if strategy == TextPlacementStrategy.text_always_below:
        return "\n".join([
            f"// Closing — page {page_num}",
            "#page[",
            f'  #box(width: 100%, height: 55%, clip: true)[#image("{img_path}", width: 100%, height: 100%, fit: "cover")]',
            "  #rect(width: 100%, height: 45%, fill: secondary)[",
            "    #align(center + horizon)[",
            "      #pad(x: 2cm)[",
            '        #text(font: heading-font, size: 22pt, weight: "bold", fill: primary)[Tamat]',
            "        #v(0.6em)",
            "        " + escaped,
            "        #v(1.5em)",
            f"        #text(size: 9pt, fill: luma(150))[{page_num}]",
            "      ]",
            "    ]",
            "  ]",
            "]",
        ])
    if strategy == TextPlacementStrategy.text_on_left:
        return "\n".join([
            f"// Closing — page {page_num}",
            "#page[",
            "  #rect(width: 100%, height: 100%, fill: secondary)[",
            "    #align(center + horizon)[",
            "      #pad(x: 2cm)[",
            '        #text(font: heading-font, size: 22pt, weight: "bold", fill: primary)[Tamat]',
            "        #v(1em)",
            "        " + escaped,
            "        #v(2em)",
            f"        #text(size: 9pt, fill: luma(150))[{page_num}]",
            "      ]",
            "    ]",
            "  ]",
            "]",
        ])
    # full_bleed closing
    return "\n".join([
        f"// Closing — page {page_num}",
        "#page[",
        f'  #image("{img_path}", width: 100%, height: 100%, fit: "cover")',
        "  #place(top + left, dy: 35%,",
        "    rect(width: 100%, height: 30%, fill: white.transparentize(15%))[",
        "      #pad(x: 2cm, y: 0.8cm)[",
        "        #align(center + horizon)[",
        '          #text(font: heading-font, size: 20pt, weight: "bold", fill: primary)[Tamat]',
        "          #v(0.4em)",
        "          " + escaped,
        "        ]",
        "      ]",
        "    ]",
        "  )",
        f"  #place(bottom + right, dx: -0.5cm, dy: -0.3cm)[#text(size: 9pt, fill: luma(100))[{page_num}]]",
        "]",
    ])


def _generate_book_typst(
    *,
    images: list[Path],
    page_texts: list[str],
    scaffold: NarrativeScaffold,
    style_lock: StyleLock,
    title: str,
    author: str,
) -> str:
    """Generate complete Typst source for a children's book."""
    strategy = style_lock.text_placement_strategy
    page_w, page_h = _PAGE_DIMS[strategy]

    parts: list[str] = [
        _typst_header(
            palette=list(style_lock.palette),
            font=style_lock.typography,
            title=title,
            author=author,
            age_group=scaffold.target_age.value,
            page_width=page_w,
            page_height=page_h,
        ),
    ]

    # Title page (uses first image)
    parts.append(_title_page(strategy, str(images[0].resolve())))

    # Story pages (images 2..N-1)
    for idx in range(1, len(images) - 1):
        parts.append("")
        parts.append(
            _story_page(
                strategy,
                img_path=str(images[idx].resolve()),
                text=page_texts[idx],
                page_num=idx + 1,
            )
        )

    # Closing page (last image)
    parts.append("")
    last = len(images) - 1
    parts.append(
        _closing_page(
            strategy,
            img_path=str(images[last].resolve()),
            text=page_texts[last],
            page_num=last + 1,
        )
    )

    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Public API — Children's book PDF assembly
# ---------------------------------------------------------------------------


def assemble_childrens_book_pdf(
    *,
    images: list[Path],
    scaffold: NarrativeScaffold,
    style_lock: StyleLock,
    title: str,
    author: str,
    output_dir: Path,
    page_texts: list[str] | None = None,
) -> Path:
    """Assemble a children's book PDF from text-free illustrations + scaffold.

    Args:
        images: Ordered list of text-free illustration image paths.
        scaffold: NarrativeScaffold with per-page structural data.
        style_lock: Locked visual parameters (palette, typography, strategy).
        title: Book title.
        author: Author name.
        output_dir: Directory to write generated .typ and .pdf files.
        page_texts: Story text per page. If None, uses scaffold
            ``checkpoint_progress`` as placeholder.

    Returns:
        Path to the generated PDF.
    """
    if page_texts is None:
        page_texts = [
            p.checkpoint_progress or f"Page {p.page}" for p in scaffold.pages
        ]

    typ_source = _generate_book_typst(
        images=images,
        page_texts=page_texts,
        scaffold=scaffold,
        style_lock=style_lock,
        title=title,
        author=author,
    )

    slug = title.lower().replace(" ", "_")[:30]
    typ_path = output_dir / f"{slug}.typ"
    pdf_path = output_dir / f"{slug}.pdf"

    typ_path.write_text(typ_source, encoding="utf-8")
    _compile_typst(typ_path, pdf_path)
    return pdf_path


# ---------------------------------------------------------------------------
# Public API — Ebook assembly (PDF + EPUB)
# ---------------------------------------------------------------------------


def assemble_ebook(
    *,
    sections: list[dict[str, str]],
    title: str,
    author: str,
    output_dir: Path,
    colors: dict[str, str] | None = None,
    fonts: dict[str, str] | None = None,
) -> dict[str, Path]:
    """Assemble an ebook as both PDF (Typst) and EPUB (ebooklib).

    Args:
        sections: List of dicts with ``title`` and ``content`` keys.
        title: Book title.
        author: Author name.
        output_dir: Directory for output files.
        colors: Optional ``primary``, ``secondary``, ``accent`` hex colors.
        fonts: Optional ``headline``, ``body`` font names.

    Returns:
        Dict with ``pdf`` and ``epub`` Path values.
    """
    colors = colors or {}
    fonts = fonts or {}

    # --- PDF via Typst (import ebook.typ template) ---
    ebook_template = (_TEMPLATES_DIR / "ebook.typ").resolve()
    chapter_lines: list[str] = []
    for section in sections:
        section_title = _escape_typst(section["title"])
        section_content = _escape_typst(section["content"])
        chapter_lines.append(f"= {section_title}")
        chapter_lines.append(section_content)
        chapter_lines.append("")

    typ_source = f'#include "{ebook_template}"\n\n' + "\n".join(chapter_lines)

    slug = title.lower().replace(" ", "_")[:30]
    typ_path = output_dir / f"{slug}.typ"
    pdf_path = output_dir / f"{slug}.pdf"
    epub_path = output_dir / f"{slug}.epub"

    typ_path.write_text(typ_source, encoding="utf-8")

    # Build --input flags for sys.inputs
    input_args: list[str] = [
        "--input", f"title={title}",
        "--input", f"author={author}",
    ]
    if "primary" in colors:
        input_args += ["--input", f"primary_color={colors['primary']}"]
    if "secondary" in colors:
        input_args += ["--input", f"secondary_color={colors['secondary']}"]
    if "accent" in colors:
        input_args += ["--input", f"accent_color={colors['accent']}"]
    if "headline" in fonts:
        input_args += ["--input", f"headline_font={fonts['headline']}"]
    if "body" in fonts:
        input_args += ["--input", f"body_font={fonts['body']}"]

    env = {**os.environ, "TYPST_FONT_PATHS": str(_FONTS_DIR)}
    result = subprocess.run(
        ["typst", "compile", "--root", "/", *input_args, str(typ_path), str(pdf_path)],
        capture_output=True,
        text=True,
        env=env,
        check=False,
    )
    if result.returncode != 0:
        logger.error("Ebook Typst compilation failed: %s", result.stderr)
        raise RuntimeError(f"Ebook Typst compilation failed: {result.stderr}")

    # --- EPUB via ebooklib ---
    book = epub.EpubBook()
    book.set_identifier(str(uuid4()))
    book.set_title(title)
    book.set_language("ms")
    book.add_author(author)

    style = epub.EpubItem(
        uid="style",
        file_name="style/default.css",
        media_type="text/css",
        content=_ebook_css().encode("utf-8"),
    )
    book.add_item(style)

    spine: list[str | epub.EpubHtml] = ["nav"]
    toc: list[epub.EpubHtml] = []

    for idx, section in enumerate(sections):
        chapter = epub.EpubHtml(
            title=section["title"],
            file_name=f"chapter_{idx + 1}.xhtml",
            lang="ms",
        )
        chapter.content = (
            f"<h1>{section['title']}</h1>"
            f"<p>{section['content']}</p>"
        ).encode("utf-8")
        chapter.add_item(style)
        book.add_item(chapter)
        spine.append(chapter)
        toc.append(chapter)

    book.toc = toc
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    book.spine = spine

    epub.write_epub(str(epub_path), book)
    return {"pdf": pdf_path, "epub": epub_path}


def _ebook_css() -> str:
    """Minimal CSS for ebook typography."""
    return (
        "body { font-family: serif; line-height: 1.6; margin: 1em; }\n"
        "h1 { font-size: 1.5em; margin-top: 2em; margin-bottom: 0.5em; }\n"
        "p { margin-bottom: 0.8em; text-indent: 1.5em; }\n"
    )


# ---------------------------------------------------------------------------
# Public API — Document PDF assembly (invoice, proposal, report, etc.)
# ---------------------------------------------------------------------------


def assemble_document_pdf(
    *,
    template_name: str,
    content: dict[str, str],
    colors: dict[str, str] | None = None,
    fonts: dict[str, str] | None = None,
    output_dir: Path,
) -> Path:
    """Assemble a business document PDF from an existing Typst template.

    Args:
        template_name: Name of the template (e.g. ``invoice``, ``proposal``).
        content: Key-value pairs passed as Typst sys.inputs.
        colors: Optional color overrides (primary, secondary, accent).
        fonts: Optional font overrides (headline, body).
        output_dir: Directory for the output PDF.

    Returns:
        Path to the generated PDF.
    """
    colors = colors or {}
    fonts = fonts or {}
    template_path = (_TEMPLATES_DIR / f"{template_name}.typ").resolve()
    if not template_path.exists():
        raise FileNotFoundError(f"Template not found: {template_path}")

    input_args: list[str] = []
    for key, value in content.items():
        input_args += ["--input", f"{key}={value}"]
    if "primary" in colors:
        input_args += ["--input", f"primary_color={colors['primary']}"]
    if "secondary" in colors:
        input_args += ["--input", f"secondary_color={colors['secondary']}"]
    if "accent" in colors:
        input_args += ["--input", f"accent_color={colors['accent']}"]
    if "headline" in fonts:
        input_args += ["--input", f"headline_font={fonts['headline']}"]
    if "body" in fonts:
        input_args += ["--input", f"body_font={fonts['body']}"]

    pdf_path = output_dir / f"{template_name}.pdf"
    env = {**os.environ, "TYPST_FONT_PATHS": str(_FONTS_DIR)}
    result = subprocess.run(
        ["typst", "compile", "--root", "/", *input_args, str(template_path), str(pdf_path)],
        capture_output=True,
        text=True,
        env=env,
        check=False,
    )
    if result.returncode != 0:
        logger.error("Document Typst compilation failed: %s", result.stderr)
        raise RuntimeError(f"Document Typst compilation failed: {result.stderr}")
    return pdf_path


# ---------------------------------------------------------------------------
# RollingContext integration
# ---------------------------------------------------------------------------


def update_rolling_context_for_page(
    ctx: RollingContext,
    page: PageScaffold,
    page_text: str,
    immutable_facts: list[str] | None = None,
) -> None:
    """Update RollingContext after producing a page.

    Adds the page content to the rolling summary, tracks characters
    as entities, and registers any immutable facts.

    Args:
        ctx: The RollingContext to update.
        page: The PageScaffold for this page.
        page_text: The generated text content for this page.
        immutable_facts: Optional list of facts to lock as immutable.
    """
    summary = (
        f"Page {page.page} ({page.emotional_beat}): {page_text}"
    )
    ctx.update(summary)

    # Track characters present on this page as entities
    for character_id in page.characters_present:
        entity = TrackedEntity(
            entity_id=character_id,
            entity_type="character",
            name=character_id,
            state={"last_emotional_beat": page.emotional_beat},
            introduced_at=ctx.current_step - 1,
            last_updated_at=ctx.current_step - 1,
        )
        ctx.add_entity(entity)

    # Register immutable facts
    if immutable_facts:
        for fact in immutable_facts:
            ctx.add_immutable_fact(fact, source=f"page_{page.page}")


# ---------------------------------------------------------------------------
# Consistency checker stub (implementation deferred to S15b)
# ---------------------------------------------------------------------------


def check_visual_consistency(
    image_a: Path,
    image_b: Path,
    threshold: float = 0.75,
) -> dict[str, bool | float]:
    """Check visual consistency between two images using CLIP similarity.

    Encodes both images via CLIP ViT-B/32 and computes cosine similarity.
    Embeddings are already L2-normalised by ``encode_image()``, so the
    dot product equals cosine similarity.

    Args:
        image_a: Path to the first image.
        image_b: Path to the second image.
        threshold: Minimum similarity score to pass (default 0.75).

    Returns:
        Dict with ``passed`` (bool) and ``similarity`` (float) keys.
    """
    from utils.retrieval import encode_image

    emb_a = encode_image(image_a.read_bytes())
    emb_b = encode_image(image_b.read_bytes())

    # Cosine similarity (embeddings are already L2-normalised)
    similarity = sum(a * b for a, b in zip(emb_a, emb_b))

    passed = similarity >= threshold
    logger.info(
        "Visual consistency: %s vs %s — %.4f (threshold=%.2f, %s)",
        image_a.name, image_b.name, similarity, threshold,
        "PASS" if passed else "FAIL",
    )
    return {"passed": passed, "similarity": similarity}
